(princ "Calculating the purchase price")
(terpri)
(princ "Enter base data:")
(terpri)
(princ "Purchase amount ") (setq amount (read))
(terpri)
(if (< amount 0) (progn (princ "Incorrect amount") (exit)))
(if (> amount 1000) (setq amount (- amount (/ amount 10))))
(princ "Purchase amount including discount: ") (write (float amount)) (princ " rubles")
