(princ "Calculating the purchase price")
(terpri)
(princ "Enter base data:")
(terpri)
(princ "Notebook price \(rub\) ") (setq not_p (read))
(terpri)
(princ "Number of notebook ") (setq not_n (read))
(terpri)
(princ "Pencil price \(rub\) ") (setq pen_p (read))
(terpri)
(princ "Number of pencil ") (setq pen_n (read))
(terpri)
(princ "Purchase value: ") (write (+ (* pen_p pen_n) (* not_p not_n) )) (princ " rubles")
