(princ "Calculating the price of the trip")
(terpri)
(princ "Enter base data:")
(terpri)
(princ "Distance to country house ") (setq distance (read))
(terpri)
(princ "Gasoline consumption per 100 km ") (setq gas_c (read))
(terpri)
(princ "Gasoline price per liter ") (setq gas_p (read))
(terpri)
(princ "Price for gasoline ") (write (float (* gas_p (* (/ gas_c 100) (* distance 2))))) (princ " rubles")
